import ContentPageLayout from '../components/ContentPageLayout'

const h1: React.CSSProperties = { fontFamily: "'Alice', serif", fontWeight: 400, fontSize: '36px', color: '#b02855', marginTop: 0, marginBottom: 24 }
const h2: React.CSSProperties = { fontFamily: "'Raleway', sans-serif", fontWeight: 300, fontSize: '28px', color: '#b02855', marginTop: 32, marginBottom: 12 }
const h3: React.CSSProperties = { fontFamily: "'Raleway', sans-serif", fontWeight: 600, fontSize: '20px', color: '#58586c', marginTop: 20, marginBottom: 8 }
const body: React.CSSProperties = { fontFamily: "'Raleway', sans-serif", fontWeight: 400, fontSize: '17px', lineHeight: '30px', color: '#323248', marginTop: 0, marginBottom: 14 }
const li: React.CSSProperties = { fontFamily: "'Raleway', sans-serif", fontWeight: 400, fontSize: '17px', lineHeight: '28px', color: '#323248', marginBottom: 6 }

export default function PrivacyPolicy() {
  return (
    <ContentPageLayout bannerImage="shutterstock_448888804.jpg" bannerAlt="Privacy Policy" showSidebar={false}>
      <h1 style={h1}>Privacy Policy</h1>
      <p style={body}><strong>Last updated: March 10, 2021</strong></p>
      <p style={body}>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
      <p style={body}>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

      <h2 style={h2}>Interpretation and Definitions</h2>
      <h3 style={h3}>Interpretation</h3>
      <p style={body}>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

      <h3 style={h3}>Definitions</h3>
      <p style={body}>For the purposes of this Privacy Policy:</p>
      <ul style={{ paddingLeft: 24, marginTop: 0, marginBottom: 14 }}>
        <li style={li}><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
        <li style={li}><strong>Company</strong> refers to Mirra Periodontal &amp; Implant Center, 720 US-377, Suite 120, Roanoke TX 76262.</li>
        <li style={li}><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li style={li}><strong>Website</strong> refers to Mirra Periodontal &amp; Implant Center, accessible from https://www.mymirraimplants.com</li>
        <li style={li}><strong>Service</strong> refers to the Website.</li>
        <li style={li}><strong>Country</strong> refers to: TX, United States.</li>
        <li style={li}><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li style={li}><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li style={li}><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
      </ul>

      <h2 style={h2}>Collecting and Using Your Personal Data</h2>
      <h3 style={h3}>Types of Data Collected</h3>
      <h3 style={{ ...h3, fontWeight: 400, fontStyle: 'italic' }}>Personal Data</h3>
      <p style={body}>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
      <ul style={{ paddingLeft: 24, marginTop: 0, marginBottom: 14 }}>
        <li style={li}>Email address</li>
        <li style={li}>First name and last name</li>
        <li style={li}>Address, State, Province, ZIP/Postal code, City</li>
        <li style={li}>Usage Data</li>
      </ul>

      <h3 style={{ ...h3, fontWeight: 400, fontStyle: 'italic' }}>Usage Data</h3>
      <p style={body}>Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

      <h3 style={{ ...h3, fontWeight: 400, fontStyle: 'italic' }}>Tracking Technologies and Cookies</h3>
      <p style={body}>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>

      <h2 style={h2}>Use of Your Personal Data</h2>
      <p style={body}>The Company may use Personal Data for the following purposes:</p>
      <ul style={{ paddingLeft: 24, marginTop: 0, marginBottom: 14 }}>
        <li style={li}>To provide and maintain our Service, including to monitor the usage of our Service.</li>
        <li style={li}>To manage Your Account and registration as a user of the Service.</li>
        <li style={li}>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
        <li style={li}>To provide You with news, special offers and general information about other goods and services.</li>
        <li style={li}>To manage Your requests to Us.</li>
      </ul>

      <h2 style={h2}>Retention of Your Personal Data</h2>
      <p style={body}>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.</p>

      <h2 style={h2}>Transfer of Your Personal Data</h2>
      <p style={body}>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>

      <h2 style={h2}>Disclosure of Your Personal Data</h2>
      <h3 style={h3}>Business Transactions</h3>
      <p style={body}>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

      <h3 style={h3}>Law Enforcement</h3>
      <p style={body}>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

      <h3 style={h3}>Other Legal Requirements</h3>
      <p style={body}>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, prevent or investigate possible wrongdoing, or protect against legal liability.</p>

      <h2 style={h2}>Security of Your Personal Data</h2>
      <p style={body}>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

      <h2 style={h2}>GDPR Privacy</h2>
      <h3 style={h3}>Legal Basis for Processing Personal Data under GDPR</h3>
      <p style={body}>We may process Personal Data under the following conditions: Consent, Performance of a contract, Legal obligations, Vital interests, Public interests, or Legitimate interests.</p>

      <h3 style={h3}>Your Rights under the GDPR</h3>
      <p style={body}>You have the right under this Privacy Policy, and by law if You are within the EU, to request access, correction, erasure, or transfer of Your Personal Data, and to withdraw Your consent.</p>

      <h2 style={h2}>CCPA Privacy</h2>
      <h3 style={h3}>Your Rights under the CCPA</h3>
      <p style={body}>Under this Privacy Policy, and by law if You are a resident of California, You have the right to notice, the right to access, the right to say no to the sale of Personal Data, the right to know about Your Personal Data, and the right to delete Personal Data.</p>
      <p style={body}>We do not sell personal information. However, the Service Providers we partner with may use technology on the Service that "sells" personal information as defined by the CCPA law.</p>

      <h2 style={h2}>Contact Us</h2>
      <p style={body}>If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul style={{ paddingLeft: 24, marginTop: 0, marginBottom: 14 }}>
        <li style={li}>By phone: <a href="tel:8177679383" style={{ color: '#3276ab' }}>817.767.9383</a></li>
        <li style={li}>By mail: 720 US-377, Suite 120, Roanoke TX 76262</li>
      </ul>
    </ContentPageLayout>
  )
}
