import ContentPageLayout from '../components/ContentPageLayout'

const h1: React.CSSProperties = { fontFamily: "'Alice', serif", fontWeight: 400, fontSize: '36px', color: '#b02855', marginTop: 0, marginBottom: 24 }
const body: React.CSSProperties = { fontFamily: "'Raleway', sans-serif", fontWeight: 400, fontSize: '17px', lineHeight: '30px', color: '#323248', marginTop: 0, marginBottom: 18 }

export default function TermsOfUse() {
  return (
    <ContentPageLayout bannerImage="shutterstock_448888804.jpg" bannerAlt="Terms of Use" showSidebar={false}>
      <h1 style={h1}>Terms of Use</h1>

      <p style={body}>1. This World Wide Web site with its home page in the domain 'https://www.mymirraimplants.com', hereinafter referred to as the Website, is an information service provided by Mirra Periodontal &amp; Implant Center at no charge to users of the World Wide Web, with the express condition that these users agree to be bound by the terms and conditions set forth in this Terms of Use Agreement. Mirra Periodontal &amp; Implant Center reserves the right to change these terms and conditions at any time, and you agree to abide by the most recent version of this Terms of Use Agreement each time you view and use the Website. You are accordingly advised to consult the Terms of Use Agreement each time you view and use the Website. Do not use the Website if you do not agree to all of the following terms and conditions.</p>

      <p style={body}>2. You acknowledge that the information on the Website is provided 'as is' for general information only. It is not intended to provide medical advice, and should not be relied upon as a substitute for consultations with qualified health professionals who are familiar with your individual medical needs. Mirra Periodontal &amp; Implant Center makes no warranties of any kind regarding this Website, including but not limited to any warranty of accuracy, completeness, currency, reliability, merchantability or fitness for a particular purpose, or any warranty that these pages, or the computer server which makes them available, are free of viruses or other harmful elements, and such warranties are expressly disclaimed.</p>

      <p style={body}>3. You agree that you will hold harmless Mirra Periodontal &amp; Implant Center and its shareholders, officers, directors, and employees from all claims arising out of or related to your access or use of, or your inability to access or use, this Website or the information contained in this Website or other websites to which it is linked, including but not limited to claims that you have found something you have heard, viewed or downloaded from this Website or any other website to which it is linked to be obscene, offensive, defamatory, or infringing upon your intellectual property rights. In no event will Mirra Periodontal &amp; Implant Center or any of the information contributors to the Website be liable to you or anyone else for any decision made or action taken by you in reliance on such information or for any consequential, special or similar damages, even if Mirra Periodontal &amp; Implant Center has been advised of the possibility of such damages.</p>

      <p style={body}>4. You acknowledge that the opinions and recommendations contained in this Website are not necessarily those of Mirra Periodontal &amp; Implant Center nor are they endorsed by Advice Media.</p>

      <p style={body}>5. Mirra Periodontal &amp; Implant Center may provide links on the Website to other websites which are not under the control of Mirra Periodontal &amp; Implant Center. In general, any website which has an address (or URL) not containing 'https://www.mymirraimplants.com' is such a website. These links are provided for convenience or reference only and are not intended as an endorsement by Mirra Periodontal &amp; Implant Center of the organization or individual operating the website or a warranty of any type regarding the website or the information on the website.</p>

      <p style={body}>6. You may provide hypertext links to this Website on another website, provided that: (a) the link be a text-only link clearly marked 'Advice Media Site', (b) the link must 'point' to the URL 'https://www.mymirraimplants.com' and not to other pages within the Website, (c) the appearance, position and other aspects of the link may not be such as to damage or dilute the goodwill associated with Mirra Periodontal &amp; Implant Center's name and trademarks, (d) the appearance, position and other aspects of the link may not create the false appearance that an entity other than Mirra Periodontal &amp; Implant Center is associated with or sponsored by Mirra Periodontal &amp; Implant Center, (e) the link, when activated by a user, must display this Website full-screen and not within a 'frame' on the linked website, and (f) Mirra Periodontal &amp; Implant Center reserves the right to revoke its consent to any link at any time at its sole discretion by amending this Terms of Use Agreement. You agree that any other hypertext links to this Website must be approved in writing by Mirra Periodontal &amp; Implant Center.</p>

      <p style={body}>7. The works of authorship contained in this Website, including but not limited to all design, text and images, are owned or licensed by Mirra Periodontal &amp; Implant Center and Advice Media, hereinafter referred to as Advice Media, or its suppliers and contributors, and may not be copied, reproduced, transmitted, displayed, performed, distributed, rented, sublicensed, altered, stored by subsequent use or otherwise used in whole or in part in any manner without Mirra Periodontal &amp; Implant Center's prior written consent, except that the user may make such temporary copies in a single computer's RAM and hard drive as is necessary to browse the Website, and that the user may produce one permanent printout of each page of the Website (unmodified in form, with a copy of this Terms of Use Agreement attached) to be used by the user for personal and non-commercial uses which do not harm the reputation of Mirra Periodontal &amp; Implant Center or Advice Media.</p>

      <p style={body}>8. This Website (excluding linked sites) is controlled by Advice Media which is headquartered in the State of New York, in the United States of America. It may be accessed from all 50 states, as well as from other countries around the world. Because each of these places has laws that may differ from those of New York, by accessing this Website you agree that the statutes and laws of the State of New York, without regard to conflicts of law principles thereof, will apply to all matters arising from or relating to the use of this Website. You also agree and hereby submit to the exclusive legal jurisdiction and venues of the Courts of Nassau County, New York and the United States District Court for the Southern District of New York with respect to such matters. Mirra Periodontal &amp; Implant Center and Advice Media make no representation that materials on the Website are appropriate or available for use in other locations, and accessing them from territories where their contents are illegal is hereby prohibited.</p>

      <p style={body}>9. Advice Media, its logo, nameplates are trademarks of Advice Media and are protected by international laws and treaty provisions.</p>

      <p style={body}>10. All text and electronic images on this Website are copyrighted materials which are either registered copyrights, unregistered common law copyrights, registered trademarks or salesmarks of Mirra Periodontal &amp; Implant Center or Advice Media, its suppliers or contributors. Any attempt to infringe upon or to circumvent these copyrights or trademarks will subject the infringing individual or organization to severe criminal and civil penalties as prescribed by law.</p>
    </ContentPageLayout>
  )
}
